name: App CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  compile_typescript:
    name: Compile TypeScript
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      -
        name: Setup Terminal
        uses: actions/checkout@v2
      -
        name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          check-latest: true
      -
        name: Setup node_modules/
        run: npm add
      -
        name: Compile TypeScript
        run: tsc

  test_app:
    name: Test App
    needs: compile_typescript
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      -
        name: Setup Terminal
        uses: actions/checkout@v2
      -
        name: Setup Node.js
        uses: actions/setup-node@v2
      -
        name: Setup node_modules/
        run: npm add
      -
        name: Test App
        run: npm run server_test
