name: App CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
#  lint:
#      name: Lint
#      runs-on: ${{ matrix.os }}
#      timeout-minutes: 60
#      strategy:
#        fail-fast: false
#        matrix:
#          os:
#            - ubuntu-latest
#            - macos-latest
#            - windows-latest
#
#      steps:
#        -
#          name: Setup Terminal
#          uses: actions/checkout@v2
#        -
#          name: Setup Node.js
#          uses: actions/setup-node@v2
#        -
#          name: Setup node_modules/
#          run: npm add
#        -
#          name: Lint
#          run: npm test

  test:
    name: Test
#    needs: lint
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        test_command:
          - npm run server_test
          - npm run server_test & sleep 60;killall node
          - npm run test

    steps:
      -
        name: Setup Terminal
        uses: actions/checkout@v2
      -
        name: Setup Node.js
        uses: actions/setup-node@v2
      -
        name: Setup node_modules/
        run: npm add
        shell: bash
      -
        name: Setup TypeScript
        if: ${{ matrix.os == 'macos-latest' }}
        run: brew install typescript
        shell: bash
      -
        name: Complie TypeScript
        run: tsc
        shell: bash
      -
        name: Test
        run: ${{ matrix.test_command }}
        shell: bash
