name: CLI CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test_Cli:
    name: Test CLI
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      -
        name: Setup Terminal
        uses: actions/checkout@v2
      -
        name: Test CLI
        run: python3 test.py
        working-directory: cli
