name: CLI CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
#  lint:
#      name: Lint
#      runs-on: ${{ matrix.os }}
#      timeout-minutes: 60
#      strategy:
#        fail-fast: false
#        matrix:
#          os:
#            - ubuntu-latest
#            - macos-latest
#            - windows-latest
#
#      steps:
#        -
#          name: Setup Terminal
#          uses: actions/checkout@v2
#        -
#          name: Setup Node.js
#          uses: actions/setup-node@v2
#        -
#          name: Setup node_modules/
#          run: npm add
#        -
#          name: Lint
#          run: npm test

  test:
    name: Test
#    needs: lint
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        installation:
          - |
            python -m pip install --upgrade pip;
            pip install flake8 pytest

            if [[ -f requirements.txt ]]
            then
              pip install -r requirements.txt;
            fi

    steps:
      -
        name: Setup Terminal
        uses: actions/checkout@v2
      -
        name: Setup Python
        uses: actions/setup-python@v2
      -
        name: Install dependencies
        run: ${{ matrix.installation }}
        working-directory: cli
        shell: bash
      -
        name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        working-directory: cli
        shell: bash
      -
        name: Lint with pyflakes
        run: pyflakes .
        working-directory: cli
        shell: bash
      -
        name: Test
        run: python3 test.py
        working-directory: cli
        shell: bash

