name: CLI CI

on:
  push:
  pull_request:
  schedule:
    # Once every 23 hours and 59 minutes
    - cron: '*/59 */23 * * *'
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      COMMANDS: commands -h

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip;
          pip install flake8 pytest

          if [[ -f requirements.txt ]]
          then
            pip install -r requirements.txt;
          fi
        working-directory: cli
        shell: bash
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . \
          --count \
          --select=E9,F63,F7,F82 \
          --show-source \
          --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . \
          --count \
          --exit-zero \
          --max-complexity=10 \
          --max-line-length=127 \
          --statistics
        working-directory: cli
        shell: bash
      - name: Lint with pyflakes
        run: pyflakes .
        working-directory: cli
      - name: Test Commands
        run: |
          alias pmm='python3 cli'
          for command in $COMMANDS
          do
            pmm $command
          done
