name: Electron App CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 20 * * *'
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
      - name: Setup node_modules/
        run: npm add
      - name: Lint
        run: npm test

  test:
    name: Test
    needs: lint
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Setup Terminal
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
      - name: Setup node_modules/
        run: npm add
      - name: Complie TypeScript
        run: tsc
      - name: Test
        run: npm test
      - name: Compile SCSS
        run: npx sass styles/scss:styles/css
        working-directory: app/electron
