name: Electron App CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 20 * * *'
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 60

    strategy:
      matrix:
        node-version:
          #- 12.x
          - 14.x
          - 16.x
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Setup node_modules/
        run: npm install
      - name: Complie TypeScript
        run: tsc
      - name: Test
        run: npm test
      - name: Compile SCSS
        run: npx sass styles/scss:styles/css
        working-directory: app/electron
