name: Attempt to update dependencies

on:
  push:
  pull_request:
  schedule:
    # Once every day at midnight UTC
    -
      cron: "*/59 * * * *"
  workflow_dispatch:

jobs:
  update:
    name: Attempt to Update
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
      max-parallel: 2
    steps:
      -
        name: Setup Terminal
        uses: actions/checkout@v2
      -
        name: Setup Node.js
        uses: actions/setup-node@v2
      -
        name: Setup node_modules/
        run: npm add
      -
        name: Update
        run: npm update
      -
        name: lint
        run: npm test
      -
        name: test
        run: npm test_app
      -
        name: commit
        run: git
